services:
  api:
    container_name: api-service
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./src/.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/google-service-account.json
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      bootstrap:
        condition: service_completed_successfully
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env
      - ./secrets/google-service-account.json:/secrets/google-service-account.json:ro

  ml:
    container_name: ml-service
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./ml:/app
      - ./secrets/google-service-account.json:/secrets/google-service-account.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/google-service-account.json
    restart: unless-stopped

  worker:
    container_name: worker-service
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m app.core.worker.entry
    working_dir: /code
    env_file:
      - ./src/.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/google-service-account.json
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      bootstrap:
        condition: service_completed_successfully
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env
      - ./secrets/google-service-account.json:/secrets/google-service-account.json:ro

  db:
    container_name: postgis-db
    image: postgis/postgis:18-3.6-alpine
    env_file:
      - ./src/.env
    volumes:
      - postgres-data:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    container_name: redis-cache
    image: redis:8.6.0-alpine3.23
    volumes:
      - redis-data:/data
    expose:
      - "6379"

  bootstrap:
    container_name: api-bootstrap
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        alembic -c alembic.ini upgrade head &&
        python -m scripts.seed_permissions &&
        python -m scripts.create_default_role &&
        python -m scripts.create_first_superuser &&
        python -m scripts.create_tier
      "
    env_file:
      - ./src/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/code/src
    working_dir: /code/src
    restart: "no"

volumes:
  postgres-data:
  redis-data:
