"""add new columns to pet_qr_default and pet_qr_preference tables

Revision ID: 03c3991207fe
Revises: e01299397241
Create Date: 2026-03-07 15:35:30.838908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c3991207fe'
down_revision: Union[str, None] = 'e01299397241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_qr_default', sa.Column('show_pet_name', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_default', sa.Column('show_pet_breed', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_default', sa.Column('show_pet_age', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_default', sa.Column('show_pet_sex', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_default', sa.Column('show_pet_weight', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_default', sa.Column('show_pet_color', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_default', sa.Column('show_pet_markings', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_default', sa.Column('show_pet_sterilized', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_default', sa.Column('show_medications', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pet_qr_default', sa.Column('show_vaccines', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pet_qr_default', sa.Column('show_allergies', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pet_qr_preference', sa.Column('show_pet_name', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_preference', sa.Column('show_pet_breed', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_preference', sa.Column('show_pet_age', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_preference', sa.Column('show_pet_sex', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_preference', sa.Column('show_pet_weight', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_preference', sa.Column('show_pet_color', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_preference', sa.Column('show_pet_markings', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_preference', sa.Column('show_pet_sterilized', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pet_qr_preference', sa.Column('show_medications', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pet_qr_preference', sa.Column('show_vaccines', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pet_qr_preference', sa.Column('show_allergies', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet_qr_preference', 'show_allergies')
    op.drop_column('pet_qr_preference', 'show_vaccines')
    op.drop_column('pet_qr_preference', 'show_medications')
    op.drop_column('pet_qr_preference', 'show_pet_sterilized')
    op.drop_column('pet_qr_preference', 'show_pet_markings')
    op.drop_column('pet_qr_preference', 'show_pet_color')
    op.drop_column('pet_qr_preference', 'show_pet_weight')
    op.drop_column('pet_qr_preference', 'show_pet_sex')
    op.drop_column('pet_qr_preference', 'show_pet_age')
    op.drop_column('pet_qr_preference', 'show_pet_breed')
    op.drop_column('pet_qr_preference', 'show_pet_name')
    op.drop_column('pet_qr_default', 'show_allergies')
    op.drop_column('pet_qr_default', 'show_vaccines')
    op.drop_column('pet_qr_default', 'show_medications')
    op.drop_column('pet_qr_default', 'show_pet_sterilized')
    op.drop_column('pet_qr_default', 'show_pet_markings')
    op.drop_column('pet_qr_default', 'show_pet_color')
    op.drop_column('pet_qr_default', 'show_pet_weight')
    op.drop_column('pet_qr_default', 'show_pet_sex')
    op.drop_column('pet_qr_default', 'show_pet_age')
    op.drop_column('pet_qr_default', 'show_pet_breed')
    op.drop_column('pet_qr_default', 'show_pet_name')
    # ### end Alembic commands ###
