"""blabla

Revision ID: 3119406ee4e2
Revises: 6578392e8b63
Create Date: 2026-03-10 04:48:53.954868

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3119406ee4e2'
down_revision: Union[str, None] = '6578392e8b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_user_linked_account_mobile_user_provider_active', 'user_linked_account', ['mobile_user_id', 'provider'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_linked_account_mobile_user_provider_active', table_name='user_linked_account', postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###
