"""add push token and notification preference

Revision ID: 544f9ed213c6
Revises: 
Create Date: 2026-01-31 21:21:38.045259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544f9ed213c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_preference_user_enabled_active', 'notification_preferences', ['user_id', 'is_enabled'], unique=False, postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('ix_notification_preferences_is_deleted'), 'notification_preferences', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_index('uq_notification_preference_user_feature_active', 'notification_preferences', ['user_id', 'feature'], unique=True, postgresql_where=sa.text('NOT is_deleted'))
    op.create_table('push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.Enum('ANDROID', 'IOS', name='push_platform_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_push_tokens_user_id_is_active_active', 'push_tokens', ['user_id', 'is_active'], unique=False, postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('ix_push_tokens_is_deleted'), 'push_tokens', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    op.create_index('uq_push_tokens_token_active', 'push_tokens', ['token'], unique=True, postgresql_where=sa.text('NOT is_deleted'))
    op.create_unique_constraint(None, 'rate_limit', ['id'])
    op.create_unique_constraint(None, 'tier', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tier', type_='unique')
    op.drop_constraint(None, 'rate_limit', type_='unique')
    op.drop_index('uq_push_tokens_token_active', table_name='push_tokens', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_is_deleted'), table_name='push_tokens')
    op.drop_index('idx_push_tokens_user_id_is_active_active', table_name='push_tokens', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_table('push_tokens')
    op.drop_index('uq_notification_preference_user_feature_active', table_name='notification_preferences', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_is_deleted'), table_name='notification_preferences')
    op.drop_index('idx_notification_preference_user_enabled_active', table_name='notification_preferences', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
