"""add reporter contact info to sighting_report

Revision ID: 6578392e8b63
Revises: c0544aa3a1e8
Create Date: 2026-03-08 17:14:44.902010

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6578392e8b63'
down_revision: Union[str, None] = 'c0544aa3a1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sighting_report', sa.Column('reporter_name', sa.Text(), server_default=sa.text('NULL'), nullable=True))
    op.add_column('sighting_report', sa.Column('reporter_email', sa.Text(), server_default=sa.text('NULL'), nullable=True))
    op.add_column('sighting_report', sa.Column('reporter_phone_number', sa.Text(), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sighting_report', 'reporter_phone_number')
    op.drop_column('sighting_report', 'reporter_email')
    op.drop_column('sighting_report', 'reporter_name')
    # ### end Alembic commands ###
