"""add account status to mobile user and add mobile user token table

Revision ID: 873793b74fe9
Revises: 6e478e860d70
Create Date: 2026-03-04 16:08:21.561769

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '873793b74fe9'
down_revision: Union[str, None] = '6e478e860d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mobile_user', sa.Column('account_status', sa.Enum('active', 'suspended', 'banned', 'deactivated', name='mobile_user_account_status_enum'), server_default=sa.text("'active'::mobile_user_account_status_enum"), nullable=False))
    op.add_column('mobile_user', sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('idx_mobile_user_is_email_verified_active', 'mobile_user', ['is_email_verified'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.drop_column('mobile_user_token', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mobile_user_token', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index('idx_mobile_user_is_email_verified_active', table_name='mobile_user', postgresql_where=sa.text('is_deleted = false'))
    op.drop_column('mobile_user', 'is_email_verified')
    op.drop_column('mobile_user', 'account_status')
    # ### end Alembic commands ###
