"""add account status to mobile user and add mobile user token table

Revision ID: 873793b74fe9
Revises: 6e478e860d70
Create Date: 2026-03-04 16:08:21.561769

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '873793b74fe9'
down_revision: Union[str, None] = '6e478e860d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

account_status_enum = sa.Enum('active', 'suspended', 'banned', 'deactivated', name='mobile_user_account_status_enum')
token_type_enum = sa.Enum('email_verification', 'email_change', 'password_reset', name='mobile_user_token_type_enum')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the mobile_user_token table (was missing from migration history)
    token_type_enum.create(op.get_bind(), checkfirst=True)
    op.create_table(
        'mobile_user_token',
        sa.Column('mobile_user_id', sa.Integer(), nullable=False),
        sa.Column('type', token_type_enum, nullable=False),
        sa.Column('token_hash', sa.String(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default=sa.text('NULL')),
        sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('NULL')),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['mobile_user_id'], ['mobile_user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('uq_mobile_user_token_hash', 'mobile_user_token', ['token_hash'], unique=True)
    op.create_index('idx_mobile_user_token_mobile_user_id', 'mobile_user_token', ['mobile_user_id'], unique=False)
    op.create_index('idx_mobile_user_token_type', 'mobile_user_token', ['type'], unique=False)
    op.create_index('idx_mobile_user_token_expires_at', 'mobile_user_token', ['expires_at'], unique=False)

    # Add columns to mobile_user
    account_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('mobile_user', sa.Column('account_status', account_status_enum, server_default=sa.text("'active'::mobile_user_account_status_enum"), nullable=False))
    op.add_column('mobile_user', sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('idx_mobile_user_is_email_verified_active', 'mobile_user', ['is_email_verified'], unique=False, postgresql_where=sa.text('is_deleted = false'))



def downgrade() -> None:
    op.drop_index('idx_mobile_user_is_email_verified_active', table_name='mobile_user', postgresql_where=sa.text('is_deleted = false'))
    op.drop_column('mobile_user', 'is_email_verified')
    op.drop_column('mobile_user', 'account_status')
    account_status_enum.drop(op.get_bind(), checkfirst=True)

    # Drop the mobile_user_token table
    op.drop_index('idx_mobile_user_token_expires_at', table_name='mobile_user_token')
    op.drop_index('idx_mobile_user_token_type', table_name='mobile_user_token')
    op.drop_index('idx_mobile_user_token_mobile_user_id', table_name='mobile_user_token')
    op.drop_index('uq_mobile_user_token_hash', table_name='mobile_user_token')
    op.drop_table('mobile_user_token')
    token_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
