"""add email_change_otp to user_token_type_enum

Revision ID: c0544aa3a1e8
Revises: f3a8583b23c6
Create Date: 2026-03-08 15:50:59.503633

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c0544aa3a1e8'
down_revision: Union[str, None] = 'f3a8583b23c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
