"""add uuid column to sighting_report table

Revision ID: d3e1245c37cd
Revises: 03c3991207fe
Create Date: 2026-03-07 16:14:15.245984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e1245c37cd'
down_revision: Union[str, None] = '03c3991207fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sighting_report', sa.Column('uuid', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sighting_report', 'uuid')
    # ### end Alembic commands ###
