"""add uuid to sighting_report_image

Revision ID: f3a8583b23c6
Revises: d3e1245c37cd
Create Date: 2026-03-07 17:19:26.166192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a8583b23c6'
down_revision: Union[str, None] = 'd3e1245c37cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sighting_report_image', sa.Column('uuid', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sighting_report_image', 'uuid')
    # ### end Alembic commands ###
