from enum import StrEnum


class ErrorCode(StrEnum):
    # -------------------------------------------------------------------------
    # Generic / Fallback
    # -------------------------------------------------------------------------
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    DATABASE_ERROR = "DATABASE_ERROR"
    DATABASE_TRANSIENT_ERROR = "DATABASE_TRANSIENT_ERROR"
    INVALID_INPUT = "INVALID_INPUT"

    # -------------------------------------------------------------------------
    # Auth — 401
    # -------------------------------------------------------------------------
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_OR_EXPIRED_TOKEN = "INVALID_OR_EXPIRED_TOKEN"
    INVALID_OR_EXPIRED_REFRESH_TOKEN = "INVALID_OR_EXPIRED_REFRESH_TOKEN"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    USER_NOT_AUTHENTICATED = "USER_NOT_AUTHENTICATED"
    AUTH_CONFLICTING_ACCOUNT = "AUTH_CONFLICTING_ACCOUNT"
    GUEST_SESSION_FAILED = "GUEST_SESSION_FAILED"
    SESSION_CREATE_FAILED = "SESSION_CREATE_FAILED"
    MISSING_PROVIDER_USER_ID = "MISSING_PROVIDER_USER_ID"
    EMAIL_NOT_IN_TOKEN = "EMAIL_NOT_IN_TOKEN"

    # Account status — returned as 401 from dependencies
    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"
    ACCOUNT_BANNED = "ACCOUNT_BANNED"
    ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    GUEST_SESSION_SUSPENDED = "GUEST_SESSION_SUSPENDED"
    GUEST_SESSION_BANNED = "GUEST_SESSION_BANNED"
    GUEST_SESSION_INACTIVE = "GUEST_SESSION_INACTIVE"

    # -------------------------------------------------------------------------
    # Permission / Forbidden — 403
    # -------------------------------------------------------------------------
    FORBIDDEN = "FORBIDDEN"
    FORBIDDEN_SUPERUSER_REQUIRED = "FORBIDDEN_SUPERUSER_REQUIRED"
    FORBIDDEN_ADMIN_REQUIRED = "FORBIDDEN_ADMIN_REQUIRED"
    FORBIDDEN_NO_ROLES_ASSIGNED = "FORBIDDEN_NO_ROLES_ASSIGNED"

    # -------------------------------------------------------------------------
    # Rate Limit — 429
    # -------------------------------------------------------------------------
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    TOO_MANY_LOGIN_ATTEMPTS = "TOO_MANY_LOGIN_ATTEMPTS"

    # -------------------------------------------------------------------------
    # Not Found — 404
    # -------------------------------------------------------------------------
    USER_NOT_FOUND = "USER_NOT_FOUND"
    PET_NOT_FOUND = "PET_NOT_FOUND"
    MISSING_REPORT_NOT_FOUND = "MISSING_REPORT_NOT_FOUND"
    SIGHTING_REPORT_NOT_FOUND = "SIGHTING_REPORT_NOT_FOUND"
    INVENTORY_ITEM_NOT_FOUND = "INVENTORY_ITEM_NOT_FOUND"
    PET_ALLERGY_NOT_FOUND = "PET_ALLERGY_NOT_FOUND"
    PET_MEDICAL_CONDITION_NOT_FOUND = "PET_MEDICAL_CONDITION_NOT_FOUND"
    PET_MEDICATION_NOT_FOUND = "PET_MEDICATION_NOT_FOUND"
    PET_SCHEDULE_NOT_FOUND = "PET_SCHEDULE_NOT_FOUND"
    VACCINATION_RECORD_NOT_FOUND = "VACCINATION_RECORD_NOT_FOUND"
    ARTICLE_NOT_FOUND = "ARTICLE_NOT_FOUND"
    TIER_NOT_FOUND = "TIER_NOT_FOUND"
    RATE_LIMIT_NOT_FOUND = "RATE_LIMIT_NOT_FOUND"
    PUSH_TOKEN_NOT_FOUND = "PUSH_TOKEN_NOT_FOUND"
    QR_PREFERENCE_NOT_FOUND = "QR_PREFERENCE_NOT_FOUND"
    ADMIN_USER_NOT_FOUND = "ADMIN_USER_NOT_FOUND"
    ADMIN_ROLE_NOT_FOUND = "ADMIN_ROLE_NOT_FOUND"
    ADMIN_PERMISSION_NOT_FOUND = "ADMIN_PERMISSION_NOT_FOUND"
    ACTION_LOG_NOT_FOUND = "ACTION_LOG_NOT_FOUND"
    LOGIN_METHOD_NOT_FOUND = "LOGIN_METHOD_NOT_FOUND"
    EMAIL_PASSWORD_ACCOUNT_NOT_FOUND = "EMAIL_PASSWORD_ACCOUNT_NOT_FOUND"
    IMAGES_TO_KEEP_NOT_FOUND = "IMAGES_TO_KEEP_NOT_FOUND"
    ATTACHMENTS_TO_KEEP_NOT_FOUND = "ATTACHMENTS_TO_KEEP_NOT_FOUND"
    PROFILE_IMAGES_TO_KEEP_NOT_FOUND = "PROFILE_IMAGES_TO_KEEP_NOT_FOUND"

    # -------------------------------------------------------------------------
    # Duplicate — 409
    # -------------------------------------------------------------------------
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    USERNAME_CONFLICT = "USERNAME_CONFLICT"
    PHONE_NUMBER_ALREADY_EXISTS = "PHONE_NUMBER_ALREADY_EXISTS"
    REGISTRATION_FAILED = "REGISTRATION_FAILED"
    EMAIL_ALREADY_CONNECTED = "EMAIL_ALREADY_CONNECTED"

    # -------------------------------------------------------------------------
    # Invalid Input — 422 (User / Auth)
    # -------------------------------------------------------------------------
    EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"
    NO_EMAIL_ON_ACCOUNT = "NO_EMAIL_ON_ACCOUNT"
    NEW_EMAIL_SAME_AS_CURRENT = "NEW_EMAIL_SAME_AS_CURRENT"
    PASSWORD_REQUIRED_FOR_EMAIL_CHANGE = "PASSWORD_REQUIRED_FOR_EMAIL_CHANGE"
    INCORRECT_CURRENT_PASSWORD = "INCORRECT_CURRENT_PASSWORD"
    PROFILE_IMAGE_UPLOAD_FAILED = "PROFILE_IMAGE_UPLOAD_FAILED"
    TOKEN_INVALID_OR_EXPIRED = "TOKEN_INVALID_OR_EXPIRED"

    # Linked accounts
    EMAIL_PASSWORD_ALREADY_LINKED = "EMAIL_PASSWORD_ALREADY_LINKED"
    EMAIL_ALREADY_LINKED_TO_ANOTHER = "EMAIL_ALREADY_LINKED_TO_ANOTHER"
    GOOGLE_ALREADY_LINKED = "GOOGLE_ALREADY_LINKED"
    GOOGLE_LINKED_TO_ANOTHER = "GOOGLE_LINKED_TO_ANOTHER"
    LAST_LOGIN_METHOD = "LAST_LOGIN_METHOD"
    PASSWORD_REQUIRED_FOR_PROVIDER_CHANGE = "PASSWORD_REQUIRED_FOR_PROVIDER_CHANGE"
    ADD_EMAIL_PASSWORD_FAILED = "ADD_EMAIL_PASSWORD_FAILED"
    ADD_GOOGLE_FAILED = "ADD_GOOGLE_FAILED"
    USER_REFERENCED_BY_OTHER_RECORDS = "USER_REFERENCED_BY_OTHER_RECORDS"

    # -------------------------------------------------------------------------
    # Invalid Input — 422 (Missing Reports)
    # -------------------------------------------------------------------------
    MISSING_REPORT_UNSUPPORTED_SPECIES = "MISSING_REPORT_UNSUPPORTED_SPECIES"
    MISSING_REPORT_ALREADY_EXISTS = "MISSING_REPORT_ALREADY_EXISTS"
    MISSING_REPORT_STATUS_FINAL = "MISSING_REPORT_STATUS_FINAL"
    MISSING_REPORT_CANNOT_REVERT_TO_LOST = "MISSING_REPORT_CANNOT_REVERT_TO_LOST"
    MISSING_REPORT_CREATE_FAILED = "MISSING_REPORT_CREATE_FAILED"
    MISSING_REPORT_UPDATE_FAILED = "MISSING_REPORT_UPDATE_FAILED"

    # -------------------------------------------------------------------------
    # Invalid Input — 422 (Pets)
    # -------------------------------------------------------------------------
    INVALID_PET_SPECIES = "INVALID_PET_SPECIES"
    PET_IMAGE_UPLOAD_FAILED = "PET_IMAGE_UPLOAD_FAILED"
    PET_IMAGE_INVALID_FORMAT = "PET_IMAGE_INVALID_FORMAT"
    PET_IMAGE_NO_PET_DETECTED = "PET_IMAGE_NO_PET_DETECTED"
    PET_CREATE_FAILED = "PET_CREATE_FAILED"

    # -------------------------------------------------------------------------
    # Invalid Input — 422 (Pet Health Records)
    # -------------------------------------------------------------------------
    PET_ALLERGY_ALREADY_EXISTS = "PET_ALLERGY_ALREADY_EXISTS"
    PET_ALLERGY_CREATE_FAILED = "PET_ALLERGY_CREATE_FAILED"
    PET_ALLERGY_UPDATE_FAILED = "PET_ALLERGY_UPDATE_FAILED"
    PET_MEDICAL_CONDITION_ALREADY_EXISTS = "PET_MEDICAL_CONDITION_ALREADY_EXISTS"
    PET_MEDICAL_CONDITION_CREATE_FAILED = "PET_MEDICAL_CONDITION_CREATE_FAILED"
    PET_MEDICAL_CONDITION_UPDATE_FAILED = "PET_MEDICAL_CONDITION_UPDATE_FAILED"
    PET_MEDICATION_ALREADY_EXISTS = "PET_MEDICATION_ALREADY_EXISTS"
    PET_MEDICATION_CREATE_FAILED = "PET_MEDICATION_CREATE_FAILED"
    PET_MEDICATION_UPDATE_FAILED = "PET_MEDICATION_UPDATE_FAILED"
    PET_SCHEDULE_CREATE_FAILED = "PET_SCHEDULE_CREATE_FAILED"
    PET_SCHEDULE_UPDATE_FAILED = "PET_SCHEDULE_UPDATE_FAILED"

    # -------------------------------------------------------------------------
    # Invalid Input — 422 (Vaccination Records)
    # -------------------------------------------------------------------------
    VACCINATION_ATTACHMENT_UPLOAD_FAILED = "VACCINATION_ATTACHMENT_UPLOAD_FAILED"
    VACCINATION_ATTACHMENT_INVALID_MIME = "VACCINATION_ATTACHMENT_INVALID_MIME"
    VACCINATION_ATTACHMENT_MISSING_MIME = "VACCINATION_ATTACHMENT_MISSING_MIME"
    VACCINATION_ATTACHMENT_LIMIT_EXCEEDED = "VACCINATION_ATTACHMENT_LIMIT_EXCEEDED"
    VACCINATION_ATTACHMENT_SIZE_EXCEEDED = "VACCINATION_ATTACHMENT_SIZE_EXCEEDED"
    VACCINATION_ATTACHMENT_INVALID_ORDER = "VACCINATION_ATTACHMENT_INVALID_ORDER"
    VACCINATION_RECORD_CREATE_FAILED = "VACCINATION_RECORD_CREATE_FAILED"
    VACCINATION_RECORD_UPDATE_FAILED = "VACCINATION_RECORD_UPDATE_FAILED"

    # -------------------------------------------------------------------------
    # Invalid Input — 422 (Inventory)
    # -------------------------------------------------------------------------
    INVENTORY_IMAGE_UPLOAD_FAILED = "INVENTORY_IMAGE_UPLOAD_FAILED"
    INVENTORY_IMAGE_INVALID_MIME = "INVENTORY_IMAGE_INVALID_MIME"
    INVENTORY_IMAGE_MISSING_MIME = "INVENTORY_IMAGE_MISSING_MIME"
    INVENTORY_IMAGE_LIMIT_EXCEEDED = "INVENTORY_IMAGE_LIMIT_EXCEEDED"
    INVENTORY_IMAGE_SIZE_EXCEEDED = "INVENTORY_IMAGE_SIZE_EXCEEDED"
    INVENTORY_IMAGE_INVALID_ORDER = "INVENTORY_IMAGE_INVALID_ORDER"
    INVENTORY_NAME_ALREADY_EXISTS = "INVENTORY_NAME_ALREADY_EXISTS"
    INVENTORY_CREATE_FAILED = "INVENTORY_CREATE_FAILED"
    INVENTORY_UPDATE_FAILED = "INVENTORY_UPDATE_FAILED"

    # -------------------------------------------------------------------------
    # Invalid Input — 422 (Sighting Reports)
    # -------------------------------------------------------------------------
    SIGHTING_IMAGE_UPLOAD_FAILED = "SIGHTING_IMAGE_UPLOAD_FAILED"
    SIGHTING_IMAGE_INVALID_MIME = "SIGHTING_IMAGE_INVALID_MIME"
    SIGHTING_IMAGE_LIMIT_EXCEEDED = "SIGHTING_IMAGE_LIMIT_EXCEEDED"
    SIGHTING_IMAGE_SIZE_EXCEEDED = "SIGHTING_IMAGE_SIZE_EXCEEDED"
    SIGHTING_IMAGE_INVALID_ORDER = "SIGHTING_IMAGE_INVALID_ORDER"
    SIGHTING_REPORT_CREATE_FAILED = "SIGHTING_REPORT_CREATE_FAILED"
    SIGHTING_REPORT_UPDATE_FAILED = "SIGHTING_REPORT_UPDATE_FAILED"

    # -------------------------------------------------------------------------
    # Invalid Input — 422 (Upload Service)
    # -------------------------------------------------------------------------
    UPLOAD_INVALID_EXTENSION = "UPLOAD_INVALID_EXTENSION"
    UPLOAD_INVALID_FILE_TYPE = "UPLOAD_INVALID_FILE_TYPE"
    UPLOAD_NO_FILES_PROVIDED = "UPLOAD_NO_FILES_PROVIDED"
    UPLOAD_TOO_MANY_FILES = "UPLOAD_TOO_MANY_FILES"

    # -------------------------------------------------------------------------
    # Invalid Input — 422 (Search Engine)
    # -------------------------------------------------------------------------
    SEARCH_UNKNOWN_FIELD = "SEARCH_UNKNOWN_FIELD"
    SEARCH_FILTER_TOO_DEEP = "SEARCH_FILTER_TOO_DEEP"
    SEARCH_EMPTY_FILTER_GROUP = "SEARCH_EMPTY_FILTER_GROUP"
    SEARCH_OPERATOR_NOT_ALLOWED = "SEARCH_OPERATOR_NOT_ALLOWED"
    SEARCH_INVALID_SORT_FIELD = "SEARCH_INVALID_SORT_FIELD"
    SEARCH_INVALID_PAGINATION = "SEARCH_INVALID_PAGINATION"
    SEARCH_INVALID_FILTER_VALUE = "SEARCH_INVALID_FILTER_VALUE"

    # -------------------------------------------------------------------------
    # Invalid Input — 422 (Admin)
    # -------------------------------------------------------------------------
    ADMIN_PERMISSION_KEY_ALREADY_EXISTS = "ADMIN_PERMISSION_KEY_ALREADY_EXISTS"
    ADMIN_PERMISSION_CREATE_FAILED = "ADMIN_PERMISSION_CREATE_FAILED"
    ADMIN_PERMISSION_UPDATE_FAILED = "ADMIN_PERMISSION_UPDATE_FAILED"
    ADMIN_ROLE_NAME_ALREADY_EXISTS = "ADMIN_ROLE_NAME_ALREADY_EXISTS"
    ADMIN_ROLE_CREATE_FAILED = "ADMIN_ROLE_CREATE_FAILED"
    ADMIN_ROLE_UPDATE_FAILED = "ADMIN_ROLE_UPDATE_FAILED"
    ADMIN_ROLE_PERMISSION_IDS_NOT_FOUND = "ADMIN_ROLE_PERMISSION_IDS_NOT_FOUND"
    ADMIN_USER_CREATE_FAILED = "ADMIN_USER_CREATE_FAILED"
    ADMIN_USER_UPDATE_FAILED = "ADMIN_USER_UPDATE_FAILED"
    ADMIN_USER_ROLE_IDS_NOT_FOUND = "ADMIN_USER_ROLE_IDS_NOT_FOUND"
    ADMIN_USER_PERMISSION_IDS_NOT_FOUND = "ADMIN_USER_PERMISSION_IDS_NOT_FOUND"
    ARTICLE_TITLE_ALREADY_EXISTS = "ARTICLE_TITLE_ALREADY_EXISTS"
    ARTICLE_CREATE_FAILED = "ARTICLE_CREATE_FAILED"
    ARTICLE_UPDATE_FAILED = "ARTICLE_UPDATE_FAILED"
    TIER_NAME_ALREADY_EXISTS = "TIER_NAME_ALREADY_EXISTS"
    TIER_CREATE_FAILED = "TIER_CREATE_FAILED"
    TIER_UPDATE_FAILED = "TIER_UPDATE_FAILED"
    RATE_LIMIT_NAME_ALREADY_EXISTS = "RATE_LIMIT_NAME_ALREADY_EXISTS"
    RATE_LIMIT_PATH_ALREADY_EXISTS = "RATE_LIMIT_PATH_ALREADY_EXISTS"
    RATE_LIMIT_CREATE_FAILED = "RATE_LIMIT_CREATE_FAILED"
    RATE_LIMIT_UPDATE_FAILED = "RATE_LIMIT_UPDATE_FAILED"

    # -------------------------------------------------------------------------
    # ML Service Errors
    # -------------------------------------------------------------------------
    ML_SERVICE_UNAVAILABLE = "ML_SERVICE_UNAVAILABLE"
    ML_SERVICE_TIMEOUT = "ML_SERVICE_TIMEOUT"
    ML_SERVICE_UNEXPECTED_RESPONSE = "ML_SERVICE_UNEXPECTED_RESPONSE"
    ML_IMAGE_PROCESSING_FAILED = "ML_IMAGE_PROCESSING_FAILED"
    ML_VECTOR_SEARCH_FAILED = "ML_VECTOR_SEARCH_FAILED"
    ML_GENERIC_ERROR = "ML_GENERIC_ERROR"
